accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path('signup/', views.signup_view, name="signup"),
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout"),
]

msg/urls.py
from . import views
from django.urls import path

app_name = 'msg'

urlpatterns = [
    path('', views.message_list, name='message_list'),
    path('message_create/', views.message_create, name="message_create"), 
    path('comment_create/<int:message_id>/', views.comment_create, name="comment_create")        
]

portfolio_page/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name='portfolio_page'
urlpatterns = [
    path('', views.index,name='homepage')
]

project1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portfolio_page.urls')),
    path('message/', include('msg.urls')),
    path('accounts/', include('accounts.urls')),
]

accounts/models.py
from django.db import models

# Create your models here.

msg/models.py
from django.db import models
from django.contrib.auth.models import User

class Message(models.Model):
    
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, default=None, on_delete=models.CASCADE,blank=True, null=True)
    def __str__(self):
        return "{} - {}".format(self.author, self.snipped_message())
    
    def snipped_message(self):
        if len(self.message) > 20 :
            return self.message[:20] + " ..."
        return self.message

class Comment(models.Model):
    comment = models.TextField(max_length=50)
    created_at = models.DateTimeField(auto_now_add=True)
    message = models.ForeignKey(Message, on_delete=models.CASCADE, blank=True, null=True, related_name="comments")
    author = models.ForeignKey(User, default=None, on_delete=models.CASCADE,blank=True, null=True)
    def __str__(self):
        return "{} - {}".format(self.author, self.comment)
    

portfolio_page/models.py
from django.db import models

# Create your models here.

msg/forms.py
from . import models
from django import forms

class CreateMessageForm(forms.ModelForm):
    class Meta:
        model = models.Message
        fields = [
            "message",
        ]

class CreateCommentForm(forms.ModelForm):
    class Meta:
        model = models.Comment
        fields=[
            "comment",
        ]

accounts/views.py
# Create your views here.
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout

def signup_view(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('msg:message_list')
    else:
        form = UserCreationForm()
    return render(request, 'accounts/signup.html', {'form':form})

def login_view(request):
    if request.method =="POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('msg:message_list')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', {'form':form})

def logout_view(request):
    if request.method == "POST":
        logout(request)
        return redirect('msg:message_list')

msg/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import Message, Comment
from .import forms
# Create your views here.
def message_list(request):
    messages = Message.objects.all()
    message_form = forms.CreateMessageForm()
    comment_form = forms.CreateCommentForm()
    response = {
        'msgs' : messages,
        'form' : message_form,
        'comment_form': comment_form
    }
    return render(request, 'msg/message_list.html', response)

@login_required(login_url="/accounts/login")
def message_create(request):
    message_form= forms.CreateMessageForm(request.POST)
    if request.method == "POST" and message_form.is_valid():
        instance = message_form.save(commit=False)
        instance.author = request.user
        instance.save()
    return redirect('msg:message_list')

def comment_create(request, message_id):
    comment_form= forms.CreateCommentForm(request.POST)
    message = Message.objects.get(pk=message_id)
    if request.method == "POST" and comment_form.is_valid():
        instance = comment_form.save(commit=False)
        instance.author = request.user
        instance.message= message
        instance.save()        
    return redirect('msg:message_list')

portfolio_page/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request,'portfolio_page/profile.html')

accounts/templates/accounts/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Login</title>
</head>
<body>
    <h1>Log In</h1>
    <form class="site-form" action="{% url 'accounts:login' %}" method="POST">
        {% csrf_token %}
        {{ form  }}
        <input type="submit" value="Log In">
    </form>
</body>
</html>

accounts/templates/accounts/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Sign Up</title>
</head>
<body>
    <h1>Sign Up</h1>
    <form class="site-form" action="/accounts/signup/" method="POST">
        {% csrf_token %}
        {{ form  }}
        <input type="submit" value="Sign Up">
    </form>
</body>
</html>

msg/templates/msg/message_list.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'msg/style.css' %}">
    <title>Message_list</title>
</head>

<body>
    <form class="logout-link" action="{% url 'accounts:logout' %}" method="POST">
            {% csrf_token %}
            <button type="submit">Log Out</button>
    </form>

    <form action="{% url 'msg:message_create' %}" method="POST">
        {% csrf_token %}
        <div>
            {% for field in form.visible_fields %}
                {{ field }}
            {% endfor %}
        </div>
        <button type="submit">Add!</button>
    </form>

   {% for message in msgs %}
   <h6>{{message.author.username}}</h6>
   <p> {{message.message}}</p>
   <p>{{message.created_at}}</p>
   <form method="POST" action="{% url 'msg:comment_create' message_id=message.id %}">
       {% csrf_token %}
       <div>
           {% for field in comment_form.visible_fields %}
            {{ field }}
           {% endfor%}
           <button type="submit">Comment</button>
       </div>
   </form>
    {% for comment in message.comments.all %}
        <div>
            {{comment.comment}} by {{comment.author.username}}
        </div>
    {% endfor %}
   {% endfor %}
</body>
</html>

portfolio_page/templates/portfolio_page/profile.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'portfolio_page/style.css' %}">
    <title>Profile</title>
</head>
<body>
    <div>
        <div class="top">
                <ul>
                    <li><a href="#home">Home</a></li>
                    <li><a href="#hobbies">Hobbies</a></li>
                    <li><a href="#skills">Skills</a></li>
                    <li><a href="#contact">Contact</a></li>
                    <li id="nama">Christopher YHT</li>
                </ul>
        </div>
        <div class="container" id="home">
            <div class="profile">
                <img src="{% static 'portfolio_page/Christo.jpg' %}" alt="Foto diri" class="profile-pic">
            </div>
            <div class="tulisan profile">
                <p>My Name is Christopher Y Hasian Tamba.<br>You can call me Christo.</p>
                <p>Born in Jakarta, 11 February 2001</p>
            </div>
        </div><hr>
        <div>
            <div id="hobbies">
                <h1 class="judul">Hobbies</h1>
                <div class="hobi border-hobi container">
                    <div>
                        <img src="{% static 'portfolio_page/gitar.jpg' %}" alt="main gitar" id="guitar">
                        <p>Guitar</p>
                    </div>
                    <div>
                        <img src="{% static 'portfolio_page/drum.jpg' %}" alt="main drum" id="drum">
                        <p>Drum</p>
                    </div>
                </div>
            </div><hr>

            <h1 class="judul" id="skills">Skills</h1>
            <div class="tulisan">
                <p>Python<br>HTML<br>Public Speaking<br>Microsoft Office</p>
            </div><hr>

            <div class="tulisan" id="contact">
                <h1 class="judul">Contact Me!</h1>
                <div class="contact">
                    <p><img src="{% static 'portfolio_page/email.png' %}" alt="Email" id="icon">christamba11@gmail.com</p>
                    <p><img src="{% static 'portfolio_page/Line.png' %}" alt="Line id" id="icon">christamba</p>
                    <p><img src="{% static 'portfolio_page/' %}" alt="Instagram" id="icon">christamba11</p>
                </div>
            </div>
            
            
        </div>
    </div>
</body>
</html>